title: "Saphid"
description: "Infrastructure, agents, and links"
theme: minima
baseurl: "/homelab-blog"
url: ""

markdown: kramdown
permalink: /:title/

header_pages:
  - index.md
  - links.html

minima:
  skin: dark
